version: '3.8'

services:

  mongo-db:
    image: mongo:6.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MG_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MG_PWD}
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017

  postgres-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
      POSTGRES_PASSWORD: ${PG_PWD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432